# Dataset

In [ ]:
datas_dir = "../../datas/raw"
filename = "2025_07_10_16.18.40.mp4"
dir_output_img = f"../../datas/preprocessing/{filename}"

In [ ]:
from stratadl.core.preprocessing.video import split_to_frames
from stratadl.core.utils.shards import create_shards_from_directory, make_dataloader, verify_distribution
from stratadl.core.utils.common import get_device

import torchvision.transforms as T

import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)

In [3]:
device = get_device()
device

device(type='cpu')

In [ ]:
# On découpe la video en une série d'images
split_to_frames(datas_dir, dir_output_img)

In [ ]:
create_shards_from_directory(dir_output_img, '../../datas/preprocessing/wds', shards_max_size=100)

DEBUG:root:Taille du Train dataset : 220
DEBUG:root:Taille du Validation dataset : 47
DEBUG:root:Taille du Test dataset : 48
DEBUG:root:Shards train créés dans ../../datas/preprocessing/wds (1 .tar)
DEBUG:root:Shards val créés dans ../../datas/preprocessing/wds (1 .tar)
DEBUG:root:Shards test créés dans ../../datas/preprocessing/wds (1 .tar)

In [ ]:
train_wards_pattern = "../../datas/preprocessing/wds/train-*.tar"
val_wards_pattern = "../../datas/preprocessing/wds/val-*.tar"
test_wards_pattern = "../../datas/preprocessing/wds/test-*.tar"

img_size = (100,100)

In [7]:
# Déclaration du pipeline de préprocessing
preproccessing = T.Compose([
    T.Resize(img_size),
    T.ToTensor() # Normalisation entre 0 et 1
])

In [8]:
verify_distribution(train_wards_pattern, transform=preproccessing)

DEBUG:root:
Plage de données (sur 220 échantillons):
DEBUG:root:   Min:  0.0392
DEBUG:root:   Max:  0.8510
DEBUG:root:   Mean: 0.4588
DEBUG:root:   Std:  0.1506
DEBUG:root:
Liste des dimensions des images:
DEBUG:root:   Shape:  (3, 48, 48)

,shard,n_images,min,max,mean,std
0,../../datas/preprocessing/wds/train-000000.tar,220.0,0.039216,0.85098,0.458775,0.150632
mean,,220.0,0.039216,0.85098,0.458775,0.150632
total_images,,220.0,,,,

In [9]:
verify_distribution(val_wards_pattern, transform=preproccessing)

DEBUG:root:
Plage de données (sur 47 échantillons):
DEBUG:root:   Min:  0.0431
DEBUG:root:   Max:  0.8549
DEBUG:root:   Mean: 0.4587
DEBUG:root:   Std:  0.1507
DEBUG:root:
Liste des dimensions des images:
DEBUG:root:   Shape:  (3, 48, 48)

,shard,n_images,min,max,mean,std
0,../../datas/preprocessing/wds/val-000000.tar,47.0,0.043137,0.854902,0.458744,0.15067
mean,,47.0,0.043137,0.854902,0.458744,0.15067
total_images,,47.0,,,,

In [10]:
verify_distribution(test_wards_pattern, transform=preproccessing)

DEBUG:root:
Plage de données (sur 48 échantillons):
DEBUG:root:   Min:  0.0431
DEBUG:root:   Max:  0.8510
DEBUG:root:   Mean: 0.4587
DEBUG:root:   Std:  0.1507
DEBUG:root:
Liste des dimensions des images:
DEBUG:root:   Shape:  (3, 48, 48)

,shard,n_images,min,max,mean,std
0,../../datas/preprocessing/wds/test-000000.tar,48.0,0.043137,0.85098,0.458728,0.150678
mean,,48.0,0.043137,0.85098,0.458728,0.150678
total_images,,48.0,,,,

In [11]:
train_loader = make_dataloader(train_wards_pattern, transform=preproccessing)
val_loader   = make_dataloader(val_wards_pattern, transform=preproccessing)
test_loader  = make_dataloader(test_wards_pattern, transform=preproccessing)